---
- hosts: localhost
  connection: local
  roles:
    - common
    - debootstrap
    - role: linux-kernel
      version: "{{ linux_4_9 }}"
      config: "{{ apu_config }}"
    - role: linux-kernel
      version: "{{ linux_4_14 }}"
      config: "{{ apu_config }}"
    - config
    - packages

#TODO: make variables visible in all roles
- hosts: chroots
  connection: chroot
  roles:
    - common
    - role: linux-install
      version: "{{ linux_4_9 }}"
    - role: linux-install
      version: "{{ linux_4_14 }}"
  tasks:
    - name: clean apt cache
      command: apt clean

- hosts: localhost
  connection: local
  tasks:

    - name: compress rootfs
      command: tar czvf rootfs-{{ ansible_date_time.date }}.tar.gz rootfs

#TODO: copy results to pxe-server
