---
- hosts: localhost
  connection: local
  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'debootstrap', tags: 'debootstrap' }
    - { role: 'linux-kernel', version: "{{ linux_4_9 }}", config: "{{ apu_config }}", tags: 'linux-kernel' }
    - { role: 'linux-kernel', version: "{{ linux_4_14 }}", config: "{{ apu_config }}", tags: 'linux-kernel' }
    - { role: 'chroot_mount', tags: 'chroot_mount' }

#TODO: make variables visible in all roles
- hosts: /tmp/rootfs
  connection: chroot
  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'config', tags: 'config' }
    - { role: 'packages', tags: 'packages' }
    - { role: 'linux-install', version: "{{ linux_4_9 }}", tags: 'linux-install' }
    - { role: 'linux-install', version: "{{ linux_4_14 }}", tags: 'linux-install' }
  tasks:
    - name: clean apt cache
      command: apt clean

- hosts: localhost
  connection: local
  roles:
    - chroot_umount
    - common
  tasks:
  # for some reason archive return error, so we use tar directly An exception
  # occurred during task execution. To see the full traceback, use -vvv. The
  # error was: OSError: [Errno 2] No such file or directory:
  # 'rootfs/sbin/runlevel'
  #
  # fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error when
  # writing tar.gz archive at rootfs-v1.0.0.tar.gz: [Errno 2] No such file or
  # directory: 'rootfs/sbin/runlevel'"}
    - name: compress rootfs
      command: tar czvf rootfs-{{ rootfs_release }}.tar.gz rootfs

    - name: preserver Xen kernel
      copy:
        src: /home/debian/scripts/rootfs/boot/xen-4.8-amd64.gz
        dest: /home/debian/scripts/xen-4.8-amd64.gz

    - name: unarchive Xen kernel
      command: gunzip /home/debian/scripts/xen-4.8-amd64.gz
      args:
        chdir: /home/debian/scripts

#TODO: copy results to pxe-server
#TODO: upload rootfs to nextcloud
#TODO: cleanup
