---
- hosts: localhost
  connection: local
  roles:
    - common
    - debootstrap
    - role: linux-kernel
      version: "{{ linux_4_9 }}"
      config: "{{ apu_config }}"
    - role: linux-kernel
      version: "{{ linux_4_14 }}"
      config: "{{ apu_config }}"
    - config
    - packages

#TODO: make variables visible in all roles
- hosts: chroots
  connection: chroot
  roles:
    - common
    - role: linux-install
      version: "{{ linux_4_9 }}"
    - role: linux-install
      version: "{{ linux_4_14 }}"
  tasks:
    - name: clean apt cache
      command: apt clean

- hosts: localhost
  connection: local
  roles:
    - common
  tasks:
  # for some reason archive return error, so we use tar directly An exception
  # occurred during task execution. To see the full traceback, use -vvv. The
  # error was: OSError: [Errno 2] No such file or directory:
  # 'rootfs/sbin/runlevel'
  #
  # fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error when
  # writing tar.gz archive at rootfs-v1.0.0.tar.gz: [Errno 2] No such file or
  # directory: 'rootfs/sbin/runlevel'"}
    - name: compress rootfs
      command: tar czvf rootfs-{{ rootfs_release }}.tar.gz rootfs
      command_warnings: False

#TODO: copy results to pxe-server
#TODO: upload rootfs to nextcloud
